[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "aws.dynamodbstreams"
version = "1.0.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.dynamodbstreams"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
